SET HOST_IP=192.168.0.5
SET STS_PORT=5000
SET STS_HTTPS_PORT=5001
SET STS_ADMIN_PORT=9000
SET STS_ADMIN_HTTPS_PORT=9001

SET USE_SSL=false

SET PROTOCOL=http
SET STS_SERVER=%PROTOCOL%://%HOST_IP%:%STS_PORT%
SET STS_ADMIN_SERVER=%PROTOCOL%://%HOST_IP%:%STS_ADMIN_PORT%

if %USE_SSL% == true (

        SET PROTOCOL=https
        SET STS_SERVER=%PROTOCOL%://%HOST_IP%:%STS_HTTPS_PORT%
        SET STS_ADMIN_SERVER=%PROTOCOL%://%HOST_IP%:%STS_ADMIN_HTTPS_PORT%
)

docker-compose down
docker rm devremoto-identity-admin -f
docker rm devremoto-identity -f

